name: Gazprea Utils Image Deployment

on:
  workflow_run:
    workflows: ["LLVM Image Deployment"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - GazUtils/Dockerfile
      - .github/workflows/gaz-utils.yml

jobs:
  build-gaz-utils:
    runs-on: self-hosted

    env:
      IMAGE_NAME: ghcr.io/cmput415/gaz-utils

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load versions from VERSIONS.env
        run: |
          source VERSIONS.env
          echo "LLVM_VERSION=$LLVM_VERSION" >> $GITHUB_ENV
          echo "ANTLR_VERSION=$ANTLR_VERSION" >> $GITHUB_ENV
          echo "DRAGON_RUNNER_VERSION=$DRAGON_RUNNER_VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set date tag
        id: date
        run: echo "tag=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            --build-arg LLVM_VERSION=$LLVM_VERSION \
            --build-arg ANTLR_VERSION=$ANTLR_VERSION \
            --build-arg DRAGON_RUNNER_VERSION=$DRAGON_RUNNER_VERSION \
            -t $IMAGE_NAME:${{ steps.date.outputs.tag }} \
            -t $IMAGE_NAME:latest \
            ./GazUtils

      - name: Push Docker image with date tag
        run: docker push $IMAGE_NAME:${{ steps.date.outputs.tag }}

      - name: Push Docker image with latest tag
        run: docker push $IMAGE_NAME:latest
